import { EditorView } from '@codemirror/view';

export const graphiteDark = EditorView.theme(
  {
    '&': {
      height: '100%',
      backgroundColor: 'var(--bg-0)',
      color: 'var(--text-0)',
    },
    '&.cm-focused': {
      outline: 'none',
    },
    '.cm-scroller': {
      fontFamily: 'var(--font-ui, "Inter Variable", system-ui, sans-serif)',
      fontSize: '15.5px',
      lineHeight: '26px',
      justifyContent: 'center',
    },
    // Раскладка метрик: вертикальные поля — на .cm-content, горизонтальные — на
    // .cm-line. drawSelection компенсирует только padding строк, поэтому боковые
    // поля на контенте растягивали бы выделение за пределы текста; вертикальные
    // margin здесь запрещены совсем — карта высот меряет border-box.
    '.cm-content': {
      maxWidth: 'calc(72ch + 48px)',
      minWidth: '0',
      flexGrow: '1',
      flexShrink: '1',
      padding: '48px 0 96px',
      fontSize: '15.5px',
      lineHeight: '26px',
      caretColor: 'var(--accent)',
    },
    '.cm-line': {
      padding: '0 24px',
    },
    '.cm-cursor, .cm-dropCursor': {
      borderLeft: '2px solid var(--accent)',
      borderRadius: '2px',
      marginLeft: '-1px',
    },
    '.cm-selectionBackground': {
      backgroundColor: 'color-mix(in srgb, var(--selection) 28%, transparent)',
    },
    '&.cm-focused .cm-selectionBackground': {
      backgroundColor: 'var(--selection-dim)',
    },
    '.cm-selectionMatch': {
      backgroundColor: 'color-mix(in srgb, var(--selection) 15%, transparent)',
    },
    '&.cm-focused .cm-matchingBracket, &.cm-focused .cm-nonmatchingBracket': {
      backgroundColor: 'color-mix(in srgb, var(--accent) 15%, transparent)',
    },
    '.cm-searchMatch': {
      backgroundColor: 'color-mix(in srgb, var(--accent) 15%, transparent)',
      outline: '1px solid color-mix(in srgb, var(--accent) 30%, transparent)',
    },
    '.cm-searchMatch.cm-searchMatch-selected': {
      backgroundColor: 'color-mix(in srgb, var(--selection) 45%, transparent)',
    },
    '.cm-panels': {
      backgroundColor: 'var(--bg-1)',
      color: 'var(--text-0)',
    },
    '.cm-panels.cm-panels-top': {
      borderBottom: '1px solid var(--stroke-0)',
    },
    '.cm-panels.cm-panels-bottom': {
      borderTop: '1px solid var(--stroke-0)',
    },
    '.cm-panel': {
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
    },
    '.cm-panel.cm-search label': {
      color: 'var(--text-1)',
    },
    '.cm-panel.cm-search button[name="close"]': {
      color: 'var(--text-1)',
    },
    '.cm-textfield': {
      backgroundColor: 'var(--bg-2)',
      border: '1px solid var(--stroke-1)',
      borderRadius: 'var(--r-xs, 6px)',
      color: 'var(--text-0)',
    },
    '.cm-button': {
      backgroundColor: 'var(--bg-3)',
      backgroundImage: 'none',
      border: '1px solid var(--stroke-1)',
      borderRadius: 'var(--r-xs, 6px)',
      color: 'var(--text-0)',
    },
    '.cm-button:active': {
      backgroundColor: 'var(--bg-4)',
    },
    '.cm-tooltip': {
      backgroundColor: 'var(--bg-2)',
      border: '1px solid var(--stroke-1)',
      borderRadius: 'var(--r-s, 10px)',
      boxShadow: 'var(--sh-2)',
      color: 'var(--text-0)',
      overflow: 'hidden',
    },
    '.cm-tooltip.cm-tooltip-autocomplete': {
      padding: '4px',
      backgroundColor: 'var(--bg-2)',
      boxShadow: 'var(--sh-3)',
      animation: 'cm-gr-pop-in 140ms cubic-bezier(0.22, 1, 0.36, 1) both',
      transformOrigin: 'top left',
    },
    '.cm-tooltip-above.cm-tooltip-autocomplete': {
      transformOrigin: 'bottom left',
    },
    '.cm-tooltip.cm-tooltip-autocomplete > ul': {
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
      minWidth: '236px',
      maxWidth: '360px',
      maxHeight: '264px',
    },
    '.cm-tooltip.cm-tooltip-autocomplete > ul > li': {
      display: 'flex',
      alignItems: 'baseline',
      gap: '10px',
      padding: '5px 9px',
      borderRadius: 'var(--r-xs, 6px)',
      fontSize: '13px',
      lineHeight: '18px',
      color: 'var(--text-1)',
      transition: 'background-color 80ms var(--ease-out), color 80ms var(--ease-out)',
    },
    '.cm-tooltip.cm-tooltip-autocomplete > ul > li:hover': {
      backgroundColor: 'color-mix(in srgb, var(--accent) 6%, transparent)',
    },
    '.cm-tooltip.cm-tooltip-autocomplete > ul > li[aria-selected]': {
      backgroundColor: 'color-mix(in srgb, var(--accent) 12%, transparent)',
      color: 'var(--text-0)',
    },
    '.cm-completionLabel': {
      flex: '0 1 auto',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    '.cm-completionDetail': {
      marginLeft: 'auto',
      flexShrink: '0',
      maxWidth: '45%',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      fontStyle: 'normal',
      fontSize: '10.5px',
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      color: 'var(--text-3)',
    },
    '.cm-completionMatchedText': {
      textDecoration: 'none',
      color: 'var(--accent)',
      fontWeight: '600',
    },
    '.cm-placeholder': {
      color: 'var(--text-2)',
    },
    '.cm-gr-h1': {
      fontSize: '28px',
      lineHeight: '34px',
      fontWeight: '650',
      letterSpacing: '-0.01em',
      color: 'var(--text-0)',
      paddingTop: '10px',
    },
    '.cm-gr-h2': {
      fontSize: '22px',
      lineHeight: '30px',
      fontWeight: '600',
      letterSpacing: '-0.01em',
      color: 'var(--text-0)',
      paddingTop: '8px',
    },
    '.cm-gr-h3': {
      fontSize: '18px',
      lineHeight: '26px',
      fontWeight: '600',
      color: 'var(--text-0)',
      paddingTop: '6px',
    },
    '.cm-gr-h4': {
      fontSize: '16px',
      lineHeight: '26px',
      fontWeight: '600',
      color: 'var(--text-1)',
    },
    '.cm-gr-h5': {
      fontSize: '15.5px',
      lineHeight: '26px',
      fontWeight: '600',
      color: 'var(--text-2)',
    },
    '.cm-gr-h6': {
      fontSize: '15.5px',
      lineHeight: '26px',
      fontWeight: '600',
      color: 'var(--text-2)',
    },
    // Объявлен до .cm-gr-mark: тильды внутри зачёркивания остаются приглушёнными.
    '.cm-gr-strike': {
      textDecoration: 'line-through',
      textDecorationColor: 'var(--text-3)',
      textDecorationThickness: '1px',
      color: 'var(--text-2)',
    },
    '.cm-gr-mark': {
      color: 'var(--text-3)',
      fontWeight: '400',
    },
    '.cm-gr-strong': {
      fontWeight: '650',
      color: 'var(--text-0)',
    },
    '.cm-gr-em': {
      fontStyle: 'italic',
    },
    '.cm-gr-code': {
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      fontSize: '0.92em',
      backgroundColor: 'var(--bg-2)',
      borderRadius: 'var(--r-xs, 6px)',
      padding: '0.08em 0.32em',
      color: 'var(--text-0)',
    },
    '.cm-gr-link': {
      color: 'var(--accent)',
      textUnderlineOffset: '2px',
    },
    '.cm-gr-tag': {
      color: 'var(--accent)',
      backgroundColor: 'color-mix(in srgb, var(--accent) 10%, transparent)',
      borderRadius: 'var(--r-full, 999px)',
      padding: '0.06em 0.45em',
    },
    '.cm-gr-list-mark': {
      color: 'var(--accent)',
    },
    // Вертикальная планка цитаты — через ::before: границы строки начинаются
    // за 24px до колонки текста, а border-left рисовался бы по краю строки.
    '.cm-gr-quote': {
      position: 'relative',
      paddingLeft: '38px',
      color: 'var(--text-1)',
      fontStyle: 'italic',
    },
    '.cm-gr-quote::before': {
      content: '""',
      position: 'absolute',
      left: '24px',
      top: '0',
      bottom: '0',
      width: '2px',
      borderRadius: '2px',
      backgroundColor: 'var(--stroke-1)',
    },
    '.cm-gr-fence': {
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      fontSize: '13.5px',
      lineHeight: '22px',
      backgroundColor: 'var(--bg-2)',
      color: 'var(--text-1)',
    },
    '.cm-gr-fence-open': {
      position: 'relative',
      paddingTop: '8px',
      borderTopLeftRadius: 'var(--r-s, 10px)',
      borderTopRightRadius: 'var(--r-s, 10px)',
    },
    '.cm-gr-fence-close': {
      paddingBottom: '8px',
      borderBottomLeftRadius: 'var(--r-s, 10px)',
      borderBottomRightRadius: 'var(--r-s, 10px)',
    },
    '.cm-gr-copy': {
      position: 'absolute',
      top: '6px',
      right: '10px',
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '24px',
      height: '24px',
      padding: '0',
      border: '1px solid var(--stroke-1)',
      borderRadius: 'var(--r-xs, 6px)',
      backgroundColor: 'var(--bg-3)',
      color: 'var(--text-1)',
      cursor: 'pointer',
      opacity: '0',
      pointerEvents: 'none',
      transform: 'translateY(-2px)',
      transition:
        'opacity 140ms var(--ease-out), transform 140ms var(--ease-out), background-color 120ms var(--ease-out), color 120ms var(--ease-out), border-color 120ms var(--ease-out)',
    },
    '.cm-gr-fence-open:hover .cm-gr-copy, .cm-gr-copy.cm-gr-copy-done': {
      opacity: '1',
      pointerEvents: 'auto',
      transform: 'translateY(0)',
    },
    '.cm-gr-copy:hover': {
      backgroundColor: 'var(--bg-4)',
      color: 'var(--text-0)',
    },
    '.cm-gr-copy:active': {
      transform: 'scale(0.94)',
    },
    // Свежая иконка при подмене innerHTML (копия ↔ галочка) въезжает «пыхом».
    '.cm-gr-copy svg': {
      animation: 'cm-gr-icon-in 180ms cubic-bezier(0.22, 1, 0.36, 1) both',
    },
    '.cm-gr-copy-done': {
      color: 'var(--ok)',
      borderColor: 'color-mix(in srgb, var(--ok) 45%, transparent)',
    },
    '.cm-gr-hr': {
      position: 'relative',
      color: 'var(--text-3)',
    },
    '.cm-gr-frontmatter': {
      position: 'relative',
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      fontSize: '12px',
      lineHeight: '19px',
      fontWeight: '400',
      fontStyle: 'normal',
      letterSpacing: '0',
      color: 'var(--text-2)',
      backgroundColor: 'color-mix(in srgb, var(--bg-2) 55%, transparent)',
      paddingLeft: '36px',
    },
    '.cm-gr-frontmatter::before': {
      content: '""',
      position: 'absolute',
      left: '24px',
      top: '0',
      bottom: '0',
      width: '2px',
      backgroundColor: 'var(--stroke-1)',
    },
    // Отбивка капсулы — padding обёртки, не margin: margin блочного виджета не
    // попадает в карту высот CodeMirror и смещает попадание кликов ниже по тексту.
    '.cm-gr-fm-wrap': {
      padding: '0 24px 14px',
    },
    '.cm-gr-fm-capsule': {
      display: 'flex',
      alignItems: 'center',
      gap: '8px',
      width: '100%',
      margin: '0',
      padding: '8px 12px',
      backgroundColor: 'var(--bg-1)',
      border: '1px solid var(--stroke-0)',
      borderRadius: 'var(--r-m, 14px)',
      color: 'var(--text-1)',
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
      cursor: 'pointer',
      userSelect: 'none',
      textAlign: 'left',
      animation: 'cm-gr-rise-in 200ms cubic-bezier(0.22, 1, 0.36, 1) both',
      transition:
        'background-color 120ms var(--ease-out), border-color 120ms var(--ease-out), transform 120ms var(--ease-out)',
    },
    '.cm-gr-fm-capsule:hover': {
      backgroundColor: 'var(--bg-2)',
      borderColor: 'var(--stroke-1)',
    },
    '.cm-gr-fm-capsule:active': {
      transform: 'scale(0.995)',
    },
    '.cm-gr-fm-capsule:hover .cm-gr-fm-chevron': {
      color: 'var(--text-1)',
      transform: 'translateY(1px)',
    },
    '.cm-gr-fm-icon': {
      display: 'inline-flex',
      color: 'var(--text-2)',
      flexShrink: '0',
    },
    '.cm-gr-fm-label': {
      fontSize: '12px',
      fontWeight: '500',
      letterSpacing: '0.02em',
      color: 'var(--text-1)',
      flexShrink: '0',
    },
    '.cm-gr-fm-count': {
      fontSize: '10.5px',
      lineHeight: '15px',
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      color: 'var(--text-2)',
      backgroundColor: 'var(--bg-3)',
      borderRadius: 'var(--r-full, 999px)',
      padding: '0 6px',
      flexShrink: '0',
    },
    '.cm-gr-fm-chips': {
      display: 'flex',
      alignItems: 'center',
      gap: '4px',
      flex: '1',
      minWidth: '0',
      overflow: 'hidden',
    },
    '.cm-gr-fm-chip': {
      fontSize: '11px',
      lineHeight: '17px',
      fontFamily: 'var(--font-mono, ui-monospace, monospace)',
      color: 'var(--text-2)',
      backgroundColor: 'var(--bg-2)',
      border: '1px solid var(--stroke-0)',
      borderRadius: 'var(--r-full, 999px)',
      padding: '0 8px',
      whiteSpace: 'nowrap',
      flexShrink: '0',
    },
    '.cm-gr-fm-chip-more': {
      backgroundColor: 'transparent',
      borderStyle: 'dashed',
    },
    '.cm-gr-fm-chevron': {
      display: 'inline-flex',
      marginLeft: 'auto',
      color: 'var(--text-3)',
      flexShrink: '0',
      transition: 'color 120ms var(--ease-out), transform 160ms var(--ease-out)',
    },
    '.cm-gr-upload': {
      display: 'inline-flex',
      alignItems: 'center',
      gap: '7px',
      verticalAlign: '-3px',
      margin: '0 2px',
      padding: '2px 10px',
      fontSize: '12px',
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
      color: 'var(--text-1)',
      backgroundColor: 'var(--bg-2)',
      border: '1px solid var(--stroke-1)',
      borderRadius: 'var(--r-full, 999px)',
      animation: 'cm-gr-rise-in 180ms cubic-bezier(0.22, 1, 0.36, 1) both',
    },
    '.cm-gr-upload-spinner': {
      width: '11px',
      height: '11px',
      flexShrink: '0',
      border: '1.5px solid var(--stroke-1)',
      borderTopColor: 'var(--accent)',
      borderRadius: 'var(--r-full, 999px)',
      animation: 'cm-gr-spin 700ms linear infinite',
    },
    '.cm-gr-img': {
      display: 'inline-flex',
      maxWidth: '100%',
      margin: '4px 0',
      verticalAlign: 'top',
      cursor: 'zoom-in',
    },
    '.cm-gr-img-el': {
      display: 'block',
      maxWidth: '100%',
      maxHeight: '340px',
      borderRadius: 'var(--r-m, 14px)',
      border: '1px solid var(--stroke-0)',
      boxShadow: 'var(--sh-1)',
      animation: 'cm-gr-rise-in 220ms cubic-bezier(0.22, 1, 0.36, 1) both',
    },
    '.cm-gr-img-loading': {
      minWidth: '220px',
      minHeight: '120px',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'var(--bg-1)',
      border: '1px solid var(--stroke-0)',
      borderRadius: 'var(--r-m, 14px)',
    },
    '.cm-gr-img-shimmer': {
      display: 'inline-flex',
      color: 'var(--text-3)',
      animation: 'cm-gr-breathe 1200ms var(--ease-inout, ease-in-out) infinite',
    },
    '.cm-gr-img-missing': {
      alignItems: 'center',
      gap: '10px',
      padding: '10px 14px',
      backgroundColor: 'var(--bg-1)',
      border: '1px dashed var(--stroke-1)',
      borderRadius: 'var(--r-m, 14px)',
      cursor: 'pointer',
      transition: 'background-color 120ms var(--ease-out), border-color 120ms var(--ease-out)',
    },
    '.cm-gr-img-missing:hover': {
      backgroundColor: 'var(--bg-2)',
      borderColor: 'var(--accent)',
    },
    '.cm-gr-img-missing-icon': {
      display: 'inline-flex',
      color: 'var(--text-2)',
      flexShrink: '0',
    },
    '.cm-gr-img-missing-text': {
      display: 'flex',
      flexDirection: 'column',
      gap: '1px',
      minWidth: '0',
    },
    '.cm-gr-img-missing-name': {
      fontSize: '12.5px',
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
      color: 'var(--text-1)',
      whiteSpace: 'nowrap',
      overflow: 'hidden',
      textOverflow: 'ellipsis',
    },
    '.cm-gr-img-missing-hint': {
      fontSize: '11px',
      fontFamily: 'var(--font-ui, system-ui, sans-serif)',
      color: 'var(--text-3)',
    },
    '.cm-gr-checkbox': {
      display: 'inline-flex',
      width: '15px',
      height: '15px',
      alignItems: 'center',
      justifyContent: 'center',
      verticalAlign: '-2px',
      border: '1.5px solid var(--stroke-1)',
      borderRadius: 'var(--r-xs, 6px)',
      color: 'transparent',
      cursor: 'pointer',
      textDecoration: 'none',
      transition: 'background-color 120ms var(--ease-out), border-color 120ms var(--ease-out)',
    },
    '.cm-gr-checkbox:hover': {
      borderColor: 'var(--accent)',
    },
    '.cm-gr-checkbox-on': {
      backgroundColor: 'var(--accent)',
      borderColor: 'var(--accent)',
      color: 'var(--bg-0)',
    },
    '.cm-gr-task-done': {
      color: 'var(--text-2)',
      textDecoration: 'line-through',
      textDecorationColor: 'var(--text-3)',
    },
    '.cm-gr-ai': {
      borderRadius: '3px',
      boxShadow: 'inset 2px 0 0 0 var(--ai)',
      animation: 'cm-gr-ai-dim 1400ms cubic-bezier(0.22, 1, 0.36, 1) forwards',
    },
    '@keyframes cm-gr-ai-dim': {
      from: { backgroundColor: 'var(--ai-dim)' },
      to: { backgroundColor: 'transparent' },
    },
    '[data-reduced-motion="true"] & .cm-gr-fm-capsule, [data-reduced-motion="true"] & .cm-gr-upload, [data-reduced-motion="true"] & .cm-gr-img-el, [data-reduced-motion="true"] & .cm-gr-img-shimmer, [data-reduced-motion="true"] & .cm-tooltip-autocomplete, [data-reduced-motion="true"] & .cm-gr-copy svg':
      {
        animation: 'none',
      },
    '@keyframes cm-gr-spin': {
      from: { transform: 'rotate(0deg)' },
      to: { transform: 'rotate(360deg)' },
    },
    '@keyframes cm-gr-icon-in': {
      from: { opacity: '0', transform: 'scale(0.55)' },
      to: { opacity: '1', transform: 'scale(1)' },
    },
    '@keyframes cm-gr-pop-in': {
      from: { opacity: '0', transform: 'translateY(-3px) scale(0.98)' },
      to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    },
    '@keyframes cm-gr-rise-in': {
      from: { opacity: '0', transform: 'translateY(3px)' },
      to: { opacity: '1', transform: 'translateY(0)' },
    },
    '@keyframes cm-gr-breathe': {
      '0%, 100%': { opacity: '0.35' },
      '50%': { opacity: '0.9' },
    },
  },
  { dark: true },
);
